### ISSUE TITLE
Main development tasks and choices tracking list

### ISSUE THREAD

**Issue by joebebel** [heliaxdev/ferveo#28]
Tracking all major tasks and decisions to be made, both roughly in order of importance.

Decisions:
- [ ] Choose a BLS signature crate/library/implementation and/or choose to write a new one #23 
- [ ] Choose symmetric key crypto primitives #10 
- [ ] Choose signature scheme for DKG participant identities #11 

Tasks:

- [ ] Implement integrate BLS signatures #23 
- [ ] Integrate threshold decryption crate and/or contribute upstream #26 
- [ ] Side-channel analysis #16 
- [ ] Implement loading of trusted setup #17 
- [ ] Implement all scalability and performance enhancements #5 
- [ ] Implement key refresh #18 
- [ ] Implement randomness beacon #27

**Comment by joebebel** [comment]
Main blockers at the moment:
- Hash to curve still not implemented
- Key-committing AEAD implementation needed
- Operations that can be parallelize should be using rayon or similar
